FROM node:11.9
LABEL maintainer="maayoko@gmail.com"

USER root
RUN apt-get update && \
    mkdir /home/node/app

COPY . /home/node/app
RUN chown -R node:node /home/node/app

USER node
WORKDIR /home/node/app
RUN yarn install && yarn build

EXPOSE 3000

CMD ["sh", "-c", "yarn start"]
